CREATE TABLE country (
  id   NUMBER NOT NULL ENABLE,
  country      VARCHAR(50) NOT NULL,
  last_update  TIMESTAMP   NOT NULL,
  CONSTRAINT COUNTRY_PK PRIMARY KEY  (id)
);

create sequence country_seq;


CREATE TABLE ADDRESS 
   (	
   ID NUMBER NOT NULL, 
	STREET VARCHAR2(50 BYTE) NOT NULL, 
	ZIP_CODE VARCHAR2(10 BYTE) NOT NULL, 
	COUNTRY_FK NUMBER NOT NULL, 
	CONSTRAINT ADDRESS_PK PRIMARY KEY (ID)
	CONSTRAINT ADDRESS_FK1 FOREIGN KEY (COUNTRY_FK)
	REFERENCES COUNTRY (ID) 
 );




create table owner(
id  Number not null,
first_name varchar(20),
last_name varchar(20),
constraint owner_pk primary key(id)
);

create table owner_address_pivot(
owner_fk number not null,
address_fk number not null,
CONSTRAINT OWNER_ADDRESS_PIVOT_PK PRIMARY KEY (OWNER_FK, ADDRESS_FK),
 CONSTRAINT OWNER_ADDRESS_PIVOT_FK1 FOREIGN KEY (OWNER_FK)
	  REFERENCES OWNER (ID),
 CONSTRAINT OWNER_ADDRESS_PIVOT_FK2 FOREIGN KEY (ADDRESS_FK)
	  REFERENCES ADDRESS (ID)
);


CREATE  TABLE users (
  username VARCHAR(45) NOT NULL ,
  password VARCHAR(45) NOT NULL ,
  enabled Number(1,0) default 1,
  PRIMARY KEY (username));
  
  CREATE TABLE user_roles (
  user_role_id Number(11) NOT NULL, 
  username VARCHAR(45) NOT NULL,
  role VARCHAR(45) NOT NULL,
  PRIMARY KEY (user_role_id),
  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username));
  
   create sequence user_roles_seq;
   
   CREATE OR REPLACE TRIGGER dept_bir 
BEFORE INSERT ON departments 
FOR EACH ROW

BEGIN
  SELECT dept_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;

   CREATE OR REPLACE TRIGGER football_off_stats_trigger 
BEFORE INSERT ON football_off_stats
FOR EACH ROW

BEGIN
  SELECT football_off_stats_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
   
   UPDATE  FOOTBALL_OFF_STATS SET ID = FOOTBALL_OFF_STATS_SEQ.NEXTVAL where id;

CREATE TABLE persistent_logins (
    username VARCHAR(64) NOT NULL,
    series VARCHAR(64) NOT NULL,
    token VARCHAR(64) NOT NULL,
    last_used TIMESTAMP NOT NULL,
    PRIMARY KEY (series)
);


create table authorities (
    username varchar(50) not null,
    authority varchar(50) not null,
    constraint fk_username2 foreign key (username) references users (username),
    constraint authorities_idx_1 unique  (username, authority)
) ;
insert into  authorities (username,authority) values ('benpoon','admin');


  CREATE OR REPLACE FORCE VIEW "OWNER_ADDRESS_VIEW" ("OWNER_ID", "First Name", "Last Name", "Address ID","Street","zipcode","country") AS
  select oa.owner_fk,o.first_name,o.last_name,oa.address_fk,a.street,a.zip_code,c.country from
  owner_address oa,owner o, address a where oa.owner_fk=owner_id and oa.address_fk=a.address_id and a.country_fk=c.country_id;
  
CREATE OR REPLACE FORCE VIEW "OWNER_ADDRESS_VIEW" ("OWNER_ID", "First Name", "Last Name", "Address ID","Street","zipcode","country") AS
  select oa.owner_fk,o.first_name,o.last_name,oa.address_fk,a.street,a.zip_code,c.country from
  owner_address oa,owner o, address a, country c where oa.owner_fk=owner_id and oa.address_fk=a.address_id and a.country_fk=c.country_id;
  
  
  
  
  
  
  
  
  
  
  
  
  FANTASY FOOTBALL
  
  create or replace function parse_homeaway (pValue varchar2)
   return varchar2
is
   v_pos3 number;
   v_pos4 number;
   team_name varchar(30);
begin

   /* Return 2nd occurrence of ' ' */
   v_pos3 := INSTR (pValue, '@', 1, 1);
   

   team_name:=SUBSTR (pValue, v_pos3, v_pos3);

   if team_name='@' then
   team_name:= 'away';
   else
    team_name:= 'home';
  end if;
   return team_name;
   
end parse_homeaway;
  
  

CREATE OR REPLACE VIEW HOME_STATS_ALL_YEARS_VIEW_2 AS 
select home.player as player, home.avgpts as home_avg, AWAY.AVGPTS as AWAY_AVG from HOME_STATS_ALL_YEARS_VIEW  HOME 
LEFT OUTER JOIN  HOME_STATS_ALL_YEARS_VIEW  AWAY on home.player=away.player where HOME.home_away='home'and  AWAY.home_away='away'; 


CREATE OR REPLACE VIEW HOME_STATS_ALL_YEARS_VIEW_2 AS 
select home.player as player, home.avgpts as home_avg, AWAY.AVGPTS as AWAY_AVG ,(select count(*) from PLAYERS_STATS_PER_GAME where player=home.player and home_away='home') as home_games, (select count(*) from PLAYERS_STATS_PER_GAME where player=home.player and home_away='away') as away_games from HOME_STATS_ALL_YEARS_VIEW  HOME 
LEFT OUTER JOIN  HOME_STATS_ALL_YEARS_VIEW  AWAY on home.player=away.player where HOME.home_away='home'and  AWAY.home_away='away'; 

create or replace view players_stats_per_game as
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.PLAYER AS PLAYER, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year);


 SELECT  PLAYER, TEAM,home_away, AVG(FPOINTS)AS AVGPTS FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.PLAYER AS PLAYER, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 PLAYER, TEAM,home_away order by player;




 select 
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.PLAYER AS PLAYER, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year);
 





select * from home_stats_all_years_view;

SELECT COUNT(PLAYER) FROM(
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.PLAYER AS PLAYER, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year));



 CREATE OR REPLACE VIEW HOME_STATS_ALL_YEARS_VIEW AS 
 SELECT  PLAYER, TEAM, HOME_AWAY, AVG(FPOINTS)AS AVGPTS, count(*) as GAME_COUNT FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.PLAYER AS PLAYER, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 PLAYER, TEAM, HOME_AWAY order by player;  


 CREATE OR REPLACE VIEW HOME_STATS_BY_YEAR_VIEW AS 
 SELECT YEAR, PLAYER, TEAm, AVG(FPOINTS)AS AVGPTS, count(*) as count FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.PLAYER AS PLAYER, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 YEAR,PLAYER, TEAM order by player;  
 
  CREATE OR REPLACE VIEW HOME_STATS_VIEW_3 AS 
 
 SELECT PLAYER, YEAR, HOME_AWAY, AVG(FPOINTS)AS AVGPTS FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.POSITION AS POSITION, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 PLAYER,YEAR,HOME_AWAY; ORDER BY POSITION;  


  CREATE OR REPLACE VIEW HOME_STATS_VIEW_POSITION AS 
 SELECT POSITION, YEAR, HOME_AWAY, AVG(FPOINTS)AS AVGPTS, count(*)as count FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.POSITION AS POSITION, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 POSITION,YEAR,HOME_AWAY ORDER BY POSITION; 

SELECT * FROM HOME_STATS_VIEW_2;


create or replace function parse_homeaway (pValue varchar2)
   return varchar2
is
   v_pos3 number;
   v_pos4 number;
   team_name varchar(30);
begin

   /* Return 2nd occurrence of ' ' */
   v_pos3 := INSTR (pValue, '@', 1, 1);
   

   team_name:=SUBSTR (pValue, v_pos3, v_pos3);

   if team_name='@' then
   team_name:= 'away';
   else
  team_name:= 'home';
  end if;
   return team_name;
   
end parse_homeaway;


=======================================================================================
create or replace procedure CALCULATE_DRAFTKING_POINTS  
IS 


CURSOR player_cur IS 
SELECT * FROM FOOTBALL_OFF_STATS for update of  DK_FPTS;
V_PLAYER_REC player_cur%ROWTYPE;
QBPOINTS FLOAT; 
WRPOINTS FLOAT;
RBPOINTS FLOAT;
TOTALPOINTS FLOAT;
QB_TD_POINTS FLOAT;
RB_TD_POINTS FLOAT;
WR_TD_POINTS FLOAT;


BEGIN

OPEN player_cur;
LOOP
FETCH player_cur INTO V_PLAYER_REC;

EXIT WHEN PLAYER_CUR%NOTFOUND;
QBPOINTS:= V_PLAYER_REC.PASS_YARDS;
QBPOINTS:=QBPOINTS*.04;


QB_TD_POINTS:=V_PLAYER_REC.PASS_TDS;
QB_TD_POINTS:=QB_TD_POINTS*4;


WRPOINTS:=V_PLAYER_REC.REC_YARDS;
WRPOINTS:=WRPOINTS*0.1;
WR_TD_POINTS:=V_PLAYER_REC.REC_TDS;
WR_TD_POINTS:=WR_TD_POINTS*6;

RBPOINTS:=V_PLAYER_REC.RUSH_YARDS;
RBPOINTS:=RBPOINTS*0.1;
RB_TD_POINTS:=V_PLAYER_REC.RUSH_TDS;
RB_TD_POINTS:=RB_TD_POINTS*6;

IF QBPOINTS IS NULL OR QBPOINTS<0 THEN
QBPOINTS:=0;
END IF;
IF WRPOINTS IS NULL OR WRPOINTS<0 THEN
WRPOINTS:=0;
END IF;
IF RBPOINTS IS NULL OR RBPOINTS<0 THEN
RBPOINTS:=0;
END IF;

IF RB_TD_POINTS IS NULL THEN
RB_TD_POINTS:=0;
END IF;
IF QB_TD_POINTS IS NULL THEN
QB_TD_POINTS:=0;
END IF;
IF WR_TD_POINTS IS NULL THEN
WR_TD_POINTS:=0;
END IF;
--bonus points --
if V_PLAYER_REC.PASS_YARDS>299 then QBPOINTS:=QBPOINTS+3;
end if;
if V_PLAYER_REC.REC_YARDS>99 then WRPOINTS:=WRPOINTS+3;
end if;
if V_PLAYER_REC.RUSH_YARDS>99 then RBPOINTS:=RBPOINTS+3;
end if;
-- point per reception --
IF V_PLAYER_REC.REC_RECPTS <> NULL THEN
WRPOINTS:=WRPOINTS+V_PLAYER_REC.REC_RECPTS;
END IF;

IF V_PLAYER_REC.PASS_INTS <> NULL THEN
QBPOINTS:=QBPOINTS-V_PLAYER_REC.PASS_INTS;
END IF;

IF QBPOINTS <0 THEN
QBPOINTS:=0;
END IF;

TOTALPOINTS:=QBPOINTS+WRPOINTS+RBPOINTS+QB_TD_POINTS+WR_TD_POINTS+RB_TD_POINTS;


--UPDATE FOOTBALL_OFF_STATS SET DK_FPTS=CASE WHEN POSITION ='QB' THEN QBPOINTS WHEN POSITION='WR' THEN WRRBPOINTS END WHERE CURRENT OF player_cur; 
UPDATE FOOTBALL_OFF_STATS set DK_FPTS=TOTALPOINTS WHERE CURRENT OF player_cur;

END LOOP;

CLOSE PLAYER_CUR;

END CALCULATE_DRAFTKING_POINTS;
====================================================


update FOOTBALL_OFF_STATS  set PLAYER=PARSE_PLAYER_NAME(PLAYER)WHERE YEAR=2015 AND WEEK>1 AND POSITION='RB';



 CREATE OR REPLACE VIEW HOME_STATS_ALL_YEARS_VIEW AS 
 SELECT  PLAYER, TEAM, HOME_AWAY, AVG(FPOINTS)AS AVGPTS, count(*) as count FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.PLAYER AS PLAYER, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 PLAYER, TEAM, HOME_AWAY order by player;  


 CREATE OR REPLACE VIEW HOME_STATS_BY_YEAR_VIEW AS 
 SELECT YEAR, PLAYER, TEAM, HOME_AWAY, AVG(FPOINTS)AS AVGPTS, count(*) as count FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.PLAYER AS PLAYER, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 YEAR,PLAYER, TEAM, HOME_AWAY order by player;  
 
  CREATE OR REPLACE VIEW HOME_STATS_VIEW_3 AS 
 
 SELECT POSITION, YEAR, HOME_AWAY, AVG(FPOINTS)AS AVGPTS FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.POSITION AS POSITION, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 POSITION,YEAR,HOME_AWAY ORDER BY POSITION;  


  CREATE OR REPLACE VIEW HOME_STATS_VIEW_3 AS 
 SELECT POSITION, YEAR, HOME_AWAY, AVG(FPOINTS)AS AVGPTS, count(*)as count FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.POSITION AS POSITION, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 POSITION,YEAR,HOME_AWAY ORDER BY POSITION; 

 CREATE OR REPLACE VIEW HOME_STATS_VIEW_2 AS 
 
 SELECT YEAR, PLAYER, TEAM, HOME_AWAY, AVG(FPOINTS)AS AVGPTS FROM (
 SELECT FOS.WEEK AS WEEK, FOS.YEAR AS YEAR, FOS.PLAYER AS PLAYER, FOS.TEAM AS TEAM, PARSE_HOMEAWAY(FS.OPPONENT) AS HOME_AWAY, FOS.DK_FPTS AS FPOINTS  FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year)) GROUP BY 
 YEAR,PLAYER, TEAM, HOME_AWAY ;  

 CREATE OR REPLACE VIEW HOME_STATS_VIEW AS 
 SELECT FOS.WEEK, FOS.YEAR, FOS.PLAYER, FOS.TEAM, FS.OPPONENT FROM 
 FOOTBALL_OFF_STATS FOS  LEFT OUTER JOIN FOOTBALL_SCHEDULE FS ON TRIM(FOS.TEAM)=TRIM(FS.TEAM) AND TRIM(FOS.week)=TRIM(fs.week) and TRIM(fos.year)=TRIM(fs.year);  
